/*
Package generator provides code generation for all Motorola 68000 operation
codes.

This package is used by m68kgen to generate opcodes.go in the m68k processor
package.
*/
package generator

import (
	"bytes"
	"errors"
	"fmt"
	"io"
)

const (
	SizeByte = iota
	SizeWord
	SizeLong
)

// See table 3-19
const (
	CondTrue = iota
	CondFalse
	CondHigh
	CondLowOrSame
	CondCarryClear
	CondCarrySet
	CondNotEqual
	CondEqual
	CondOverflowClean
	CondOverflowSet
	CondPlus
	CondMinus
	CondGreaterOrEqual
	CondLessThan
	CondGreaterThan
	CondLessOrEqual
)

// See section 1.1.4
const (
	StatusCarry    = 1 << iota // C
	StatusOverflow             // V
	StatusZero                 // Z
	StatusNegative             // N
	StatusExtend               // X
)

type EffectiveAddressMask int

// See table 2-4
const (
	EADataRegister = EffectiveAddressMask(1) << iota
	EAAddressRegister
	EAAddressRegisterIndirect
	EAAddressRegisterIndirectPostInc
	EAAddressRegisterIndirectPreDec
	EAAddressRegisterIndirectDisplace
	EAAddressRegisterIndex
	EAProgramCounterIndirectDisplace
	EAProgramCounterIndex
	EAAbsoluteShort
	EAAbsoluteLong
	EAImmediate

	EAControlModes = EAAddressRegisterIndex |
		EAAddressRegisterIndirectDisplace |
		EAAddressRegisterIndex |
		EAAbsoluteLong |
		EAAbsoluteShort |
		EAProgramCounterIndirectDisplace |
		EAProgramCounterIndex
)

var RegisterMasks = []uint32{
	0xFFFFFF00, // byte
	0xFFFF0000, // word
	0x00,       // long
}

var SizeTypes = []string{
	"byte",   // byte
	"uint16", // word
	"uint32", // long
}

var SizeLengths = []int{
	1, // SizeByte
	2, // SizeWord
	4, // SizeLong
}

var (
	errNotImplemented = errors.New("not implemented")
	errInvalidOpSize  = errors.New("invalid operand size")
	errInvalidAddress = errors.New("invalid effect address")
)

type genFunc func(uint16) (string, error)

// Generate writes Go code to the given Writer which implements all supported
// 68000 operation codes.
func Generate(w io.Writer) error {
	printFileHdr(w)

	opcodes := make([]bool, 0x10000)
	for op := uint16(0x0000); op < 0xFFFF; op++ {
		fn, err := dispatch(op)
		if err == nil {
			w.Write([]byte(fn))
			// opcodes[ = append(opcodes, op)]
			opcodes[op] = true
		}
	}

	fmt.Fprintf(w, "func (c *Processor) mapFn(op uint16) func() {\n")
	// fmt.Fprintf(w, "	table := map[uint16]func(){\n")
	fmt.Fprintf(w, "	return []func(){\n")
	for i := 0; i < len(opcodes); i++ {
		if opcodes[i] {
			fmt.Fprintf(w, "		c.op%04X,\n", i)
		} else {
			fmt.Fprintf(w, "		nil,\n")
		}
		// fmt.Fprintf(w, "		0x%04X: c.op%04X,\n", opcodes[i], opcodes[i])
	}
	fmt.Fprintf(w, "	}[op]\n")
	fmt.Fprintf(w, "}\n")
	return nil
}

func dispatch(op uint16) (s string, err error) {
	funcs := []genFunc{
		genORI, genMove, genTrap, gen04, gen06, gen4E,
	}
	for _, fn := range funcs {
		s, err = fn(op)
		if err == errNotImplemented {
			continue
		}
		if err == nil {
			return
		}
		// TODO: handle error
		// fmt.Fprintf(os.Stderr, "Opcode %04X: %v\n", op, err)
	}
	err = errNotImplemented
	return
}

func allowEffectiveAddress(ea byte, mask EffectiveAddressMask) bool {
	mod := ea & 0x38 >> 3
	reg := ea & 0x07
	switch mod {
	default:
		return false
	case 0x00:
		return mask&EADataRegister != 0
	case 0x01:
		return mask&EAAddressRegister != 0
	case 0x02:
		return mask&EAAddressRegisterIndirect != 0
	case 0x03:
		return mask&EAAddressRegisterIndirectPostInc != 0
	case 0x04:
		return mask&EAAddressRegisterIndirectPreDec != 0
	case 0x05:
		return mask&EAAddressRegisterIndirectDisplace != 0
	case 0x06:
		return mask&EAAddressRegisterIndex != 0
	case 0x07:
		switch reg {
		default:
			return false
		case 0x00:
			return mask&EAAbsoluteShort != 0
		case 0x01:
			return mask&EAAbsoluteLong != 0
		case 0x02:
			return mask&EAProgramCounterIndirectDisplace != 0
		case 0x03:
			return mask&EAProgramCounterIndex != 0
		case 0x04:
			return mask&EAImmediate != 0
		}
	}
}

func bufWriter() *IndentWriter {
	return NewIndentWriter(&bytes.Buffer{}, "\t", 0)
}

func printFileHdr(w io.Writer) {
	hdr := `package m68k

/**
 * This file is generated by m68kgen
 * Hand written changes will be overwritten!
 */

import (
	"io"
)

`
	fmt.Fprintf(w, hdr)
}

func printOpFuncHdr(w io.Writer, op uint16) {
	fmt.Fprintf(w, "func (c *Processor) op%04X() {\n", op)
	fmt.Fprintln(w, "	pc := c.PC")
	fmt.Fprintln(w, "	c.PC += 2")
}

func printOpFuncFtr(w io.Writer, t *traceMessage) {
	fmt.Fprintf(w, "	%s\n", t)
	fmt.Fprint(w, "}\n\n")
}

type traceMessage struct {
	op, src, dst string
	sz           uint16
	args         []string

	noSize bool
}

func (t *traceMessage) String() string {
	args := &bytes.Buffer{}
	for i := 0; i < len(t.args); i++ {
		fmt.Fprintf(args, ", %s", t.args[i])
	}
	operands := t.dst
	if t.dst == "" {
		operands = t.src
	} else if t.src != "" {
		operands = fmt.Sprintf("%s,%s", t.src, t.dst)
	}
	if t.noSize {
		return fmt.Sprintf("c.tracef(\"%%04X %s %s\\n\", pc%s)", t.op, operands, args)
	}
	sz := []string{"b", "w", "l"}[t.sz]
	return fmt.Sprintf("c.tracef(\"%%04X %s.%s %s\\n\", pc%s)", t.op, sz, operands, args)
}

func printReadMem(w io.Writer, name, addr string, sz uint16) {
	n := []int{1, 2, 4}[sz]
	fmt.Fprintf(w, "_, c.err = c.M.Read(int(%s), c.buf[:%d])\n", addr, n)
	fmt.Fprintln(w, "if c.err != nil {")
	fmt.Fprintln(w, "	return")
	fmt.Fprintln(w, "}")
	switch sz {
	case 0:
		fmt.Fprintln(w, name, ":= c.buf[0]")
	case 1:
		fmt.Fprintln(w, name, ":= uint16(c.buf[0])<<8 | uint16(c.buf[1])")
	case 2:
		fmt.Fprintln(w, name, ":= uint32(c.buf[3]) | uint32(c.buf[2])<<8 | uint32(c.buf[1])<<16 | uint32(c.buf[0])<<24")
	}
}

func printReadImm(w io.Writer, name string, sz uint16) {
	n := []int{2, 2, 4}[sz] // single bytes are 16bit aligned
	fmt.Fprintf(w, "_, c.err = c.M.Read(int(c.PC), c.buf[:%d])\n", n)
	fmt.Fprintln(w, "if c.err != nil {")
	fmt.Fprintln(w, "	return")
	fmt.Fprintln(w, "}")
	fmt.Fprintf(w, "c.PC += %d\n", n)
	switch sz {
	case SizeByte:
		fmt.Fprintln(w, name, ":= c.buf[1]")
	case SizeWord:
		fmt.Fprintln(w, name, ":= uint16(c.buf[0])<<8 | uint16(c.buf[1])")
	case SizeLong:
		fmt.Fprintln(w, name, ":= uint32(c.buf[0])<<24 | uint32(c.buf[1])<<16 | uint32(c.buf[2])<<8 | uint32(c.buf[3])")
	}
}

// func printWriteMem(w io.Writer, addr string, sz uint16) {
// 	n := []int{1, 2, 4}[sz]
// 	switch sz {
// 	case 0: // byte
// 		fmt.Println(w, "c.buf[0] = byte(v)")

// 	case 1: // word
// 		fmt.Println(w, "c.buf[0] = byte(v >> 8)")
// 		fmt.Println(w, "c.buf[1] = byte(v)")

// 	case 2: // long
// 		fmt.Println(w, "c.buf[0] = byte(v >> 24)")
// 		fmt.Println(w, "c.buf[1] = byte(v >> 16)")
// 		fmt.Println(w, "c.buf[2] = byte(v >> 8)")
// 		fmt.Println(w, "c.buf[3] = byte(v)")
// 	}
// 	fmt.Fprintf(w, "_, c.err = c.M.Write(int(%s), c.buf[:%d]\n", addr, n)
// 	fmt.Fprintln(w, "if c.err != nil {")
// 	fmt.Fprintln(w, "	return")
// 	fmt.Fprintln(w, "}")
// }

func printSourceRead(w io.Writer, name string, ea byte, sz uint16, t *traceMessage) (err error) {
	mod := ea & 0x38 >> 3
	reg := ea & 0x07

	switch mod {
	default:
		return errInvalidAddress

	case 0x00: // data register
		fmt.Fprintf(w, "%s := c.D[%d]\n", name, reg)
		t.src = fmt.Sprintf("D%d", reg)

	case 0x01: // address register
		fmt.Fprintf(w, "%s := c.A[%d]\n", name, reg)
		t.src = fmt.Sprintf("A%d", reg)

	case 0x02: // memory address
		printReadMem(w, name, fmt.Sprintf("c.A[%d]", reg), sz)
		t.src = fmt.Sprintf("(A%d)", reg)

	case 0x03: // address indirect with post-increment
		printReadMem(w, name, fmt.Sprintf("c.A[%d]", reg), sz)
		inc := SizeLengths[sz]
		if reg == 0x07 && sz == 0 {
			// align stack pointer to 16-bit boundary (see: 2.2.4)
			inc = 2
		}
		fmt.Fprintf(w, "c.A[%d] += %d\n", reg, inc)
		t.src = fmt.Sprintf("(A%d)+", reg)

	case 0x04: // address indirect with pre-decrement
		inc := SizeLengths[sz]
		if reg == 0x07 && sz == 0 {
			// align stack pointer to 16-bit boundary (see: 2.2.4)
			inc = 2
		}
		fmt.Fprintf(w, "c.A[%d] -= %d\n", reg, inc)
		printReadMem(w, name, fmt.Sprintf("c.A[%d]", reg), sz)
		t.src = fmt.Sprintf("-(A%d)", reg)

	case 0x07:
		switch reg {
		default:
			return errInvalidAddress

		case 0x00, 0x01: // absolute short/long
			printReadImm(w, name, sz)
			t.src = "$%X"
			t.args = append(t.args, name)

		case 0x02: // program counter with displacement
			printReadImm(w, "d", SizeWord)
			fmt.Fprintf(w, "%s := c.PC + uint32(d) - 2\n", name) // -2 because readImm bumped the PC
			t.src = "$%X(PC)"
			t.args = append(t.args, "d")

		case 0x04: // immediate
			printReadImm(w, name, sz)
			t.src = "#$%X"
			t.args = append(t.args, name)
		}
	}
	return
}

func printDestRead(w io.Writer, name string, ea byte, sz uint16, t *traceMessage) (err error) {
	mod := ea & 0x38 >> 3
	reg := ea & 0x07

	switch mod {
	default:
		return errInvalidAddress

	case 0x00: // data register
		fmt.Fprintf(w, "%s := c.D[%d]\n", name, reg)
		t.dst = fmt.Sprintf("D%d", reg)

	case 0x01: // address register
		fmt.Fprintf(w, "%s := c.A[%d]\n", name, reg)
		t.dst = fmt.Sprintf("A%d", reg)

	case 0x02: // memory address
		printReadMem(w, name, fmt.Sprintf("c.A[%d]", reg), sz)
		t.dst = fmt.Sprintf("(A%d)", reg)

	case 0x07:
		switch reg {
		default:
			return errInvalidAddress

		case 0x00, 0x01: // absolute short/long
			printReadImm(w, name, sz)
			t.dst = "$%X"
			t.args = append(t.args, name)

		case 0x04: // immediate
			printReadImm(w, name, sz)
			t.dst = "#$%X"
			t.args = append(t.args, name)
		}
	}
	return
}

func printDestWrite(w io.Writer, ea byte, t *traceMessage) (err error) {
	mod := ea & 0x38 >> 3
	reg := ea & 0x07
	switch mod {
	default:
		return errInvalidAddress

	case 0x00: // data register
		// TODO: sign extension
		fmt.Fprintf(w, "c.D[%d] = uint32(v)\n", reg)
		t.dst = fmt.Sprintf("D%d", reg)

	case 0x01: // address register
		fmt.Fprintf(w, "c.A[%d] = uint32(v)\n", reg)
		t.dst = fmt.Sprintf("A%d", reg)
		t.op = "movea"

	case 0x02: // memory address
		fmt.Fprintf(w, "c.writeLong(c.A[%d], uint32(v))\n", reg)
		t.dst = fmt.Sprintf("(A%d)", reg)

	case 0x03: // memory address with post-increment
		fmt.Fprintf(w, "c.writeLong(c.A[%d], uint32(v))\n", reg)
		fmt.Fprintf(w, "c.A[%d] += 4\n", reg)
		t.dst = fmt.Sprintf("(A%d)+", reg)

	case 0x04: // memory address with pre-decrement
		fmt.Fprintf(w, "c.A[%d] -= 4\n", reg)
		fmt.Fprintf(w, "c.writeLong(c.A[%d], uint32(v))\n", reg)
		t.dst = fmt.Sprintf("-(A%d)", reg)

	case 0x05: // memory address with displacement
		printReadImm(w, "disp", SizeWord)
		fmt.Fprintf(w, "addr := uint32(disp) + c.A[%d]\n", reg)
		fmt.Fprint(w, "c.writeLong(addr, uint32(v))\n")
		t.dst = fmt.Sprintf("(%%d,A%d)", reg)
		t.args = append(t.args, "disp")

	case 0x07: // other
		switch reg {
		default:
			return errInvalidAddress

		case 0x00: // absolute word
			printReadImm(w, "addr", SizeWord)
			fmt.Fprint(w, "c.writeLong(uint32(addr), uint32(v))\n")
			t.dst = "$%X"
			t.args = append(t.args, "addr")

		case 0x01: // absolute long
			printReadImm(w, "addr", SizeLong)
			fmt.Fprint(w, "c.writeLong(addr, uint32(v))\n")
			t.dst = "$%X"
			t.args = append(t.args, "addr")
		}
	}
	return
}

func genMove(op uint16) (fn string, err error) {
	if op&0xC000 != 0 {
		err = errNotImplemented
		return
	}
	src := byte(op & 0x003F)
	dst := byte((op&0x01C0)>>3 | (op&0x0E00)>>9)

	// Decode operand size
	// Move employs an usual encoding of the operand size field. The last step
	// here normalizes this unusual size value to the same encoding used by other
	// instructions.
	sz := (op & 0x3000) >> 12
	if sz == 0 {
		err = errInvalidOpSize
		return
	}
	sz = []uint16{0, 0, 2, 1}[sz]

	t := &traceMessage{
		op: "move",
		sz: sz,
	}
	if src&0x38 == 0x08 && dst&0x20 == 0x20 {
		t.op = "movep"
	}
	if dst&0x38 == 0x08 {
		t.op = "movea"
	}
	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)
	if err = printSourceRead(w, "v", src, sz, t); err != nil {
		return
	}
	// reset status register
	fmt.Fprintln(w, "c.SR &= 0xFFFFFFF0")
	fmt.Fprintln(w, "if v == 0 {")
	fmt.Fprintln(w, "	c.SR |= 0x04")
	fmt.Fprintln(w, "}")
	// TODO: set status bit for negative values
	if err = printDestWrite(w, dst, t); err != nil {
		return
	}
	w.Decrement(1)
	printOpFuncFtr(w, t)
	return w.String(), nil
}

// genORI implements the following operations:
// - ORI to SR		4-155
// - ORI to SR		6-27
// - ORI					4-153
// - ANDI to SR		4-20
// - ANDI to SR		6-2
// - ANDI					4-18
// - SUBI
// - ADDI
func genORI(op uint16) (fn string, err error) {
	if op&0xF000 != 0 {
		err = errNotImplemented
		return
	}
	mod := (op & 0x38) >> 3
	reg := op & 0x07
	sz := (op & 0xC0) >> 6
	if sz == 0x03 {
		err = errNotImplemented
		return
	}
	t := &traceMessage{
		op:   "?",
		sz:   sz,
		src:  "#$%X",
		args: []string{"src"},
	}
	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)

	// read source (always an immediate value)
	printReadImm(w, "src", sz)

	// dest could be EA, SR or SR
	if mod == 0x07 && reg == 0x04 {
		switch sz {
		default:
			err = errNotImplemented
			return

		case 0x00: // byte to CCR
			t.dst = "CCR"
			fmt.Fprintln(w, "c.SR |= (uint32(src) & 0x1F)")

		case 0x01: // word to SR
			// TODO: Is ORI to SR a supervisor only function?
			t.dst = "SR"
			fmt.Fprintln(w, "c.SR |= uint32(src) & 0x1F")
		}
	} else {
		// TODO: eliminate where source and destination are the same

		// read destination
		if err = printDestRead(w, "dst", byte(op), sz, t); err != nil {
			return
		}

		// mutate destination
		szt := SizeTypes[sz]
		mask := RegisterMasks[sz]
		switch op & 0x0E00 { // bits 5 - 7
		default:
			err = errNotImplemented
			return

		case 0x0000: // ori
			t.op = "ori"
			fmt.Fprintf(w, "v := %s(dst) | %s(src)\n", szt, szt)

		case 0x0200: // andi
			t.op = "andi"
			// we need to ensure that only the bits for the target operand size are
			// modified in register operations.
			if mod < 2 && sz < 2 { // data or address register
				fmt.Fprintf(w, "v := (dst & 0x%X) | uint32(%s(dst)&%s(src))\n", mask, szt, szt)
			} else {
				fmt.Fprintf(w, "v := %s(dst) & %s(src)\n", szt, szt)
			}

		case 0x0400: // subi
			t.op = "subi"
			fmt.Fprintf(w, "v := %s(dst) - %s(src)\n", szt, szt)

		case 0x0600: // addi
			t.op = "addi"
			fmt.Fprintf(w, "v := %s(dst) + %s(src)\n", szt, szt)

		case 0x0900: // eori
			t.op = "eori"
			fmt.Fprintf(w, "v := %s(dst) ^ %s(src)\n", szt, szt)

		}

		// write to destination
		if err = printDestWrite(w, byte(op), t); err != nil {
			return
		}
	}

	w.Decrement(1)
	printOpFuncFtr(w, t)
	return w.String(), nil
}

// genTrap implements the following operations:
// - TRAP						4-118
//
func genTrap(op uint16) (fn string, err error) {
	if op&0xFFF0 != 0x4E40 {
		err = errNotImplemented
		return
	}
	vec := (op & 0x00F)
	t := &traceMessage{
		op:     "trap",
		src:    fmt.Sprintf("#%d", vec),
		noSize: true,
	}
	vec += 32

	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)

	// TODO: traps should do something
	fmt.Fprintf(w, "if c.handlers[%d] != nil {\n", vec)
	w.Increment(1)
	fmt.Fprintf(w, "c.err = c.handlers[%d].Exception(c, %d)\n", vec, vec)
	w.Decrement(1)
	fmt.Fprintln(w, "}")

	w.Decrement(1)
	printOpFuncFtr(w, t)
	return w.String(), nil
}

func gen04(op uint16) (fn string, err error) {
	err = errNotImplemented
	if op&0xF000 != 0x4000 {
		return
	}

	// lea always sets bits 6 - 8 to 111
	if op&0x01C0 == 0x01C0 {
		fn, err = genLea(op)
		return
	}
	return
}

// genLea implements the following operations:
// - LEA					4-110
func genLea(op uint16) (fn string, err error) {
	err = errNotImplemented
	ea := byte(op & 0x3F)
	if !allowEffectiveAddress(ea, EAControlModes) {
		return
	}
	an := (op & 0x0E00) >> 9
	t := &traceMessage{
		op:     "lea",
		dst:    fmt.Sprintf("A%d", an),
		noSize: true,
	}
	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)
	if err = printSourceRead(w, "addr", ea, SizeLong, t); err == errInvalidAddress {
		return
	}
	fmt.Fprintf(w, "c.A[%d] = addr\n", an)
	w.Decrement(1)
	printOpFuncFtr(w, t)
	return w.String(), nil
}

// gen06 implements operations starting in 0110
func gen06(op uint16) (fn string, err error) {
	err = errNotImplemented
	if op&0xF000 != 0x6000 {
		return
	}
	cnd := op & 0x0F00
	if cnd == 0x01 { // BSR
		return
	}
	fn, err = genBcc(op)
	return
}

// genBcc implements:
// - Bcc (4-25)
// - BRA (4-55)
func genBcc(op uint16) (fn string, err error) {
	cc := op & 0x0F00 >> 8
	ops := []string{
		"bra", // bra
		"bsr", // bsr (this should never happen)
		"bhi", // high
		"bls", // low or same
		"bcc", // (hi) carry clear
		"bcs", // (lo) carry set
		"bne", // not equal
		"beq", // equal
		"bvc", // overflow clear
		"bvs", // overflow set
		"bpl", // plus
		"bmi", // minus
		"bge", // greater or equal
		"blt", // less than
		"bgt", // greater than
		"ble", // less or equal
	}[cc]

	// TODO: implement other conditions
	switch cc {
	case 0x00:
	case 0x07:
		// continue

	default:
		err = errNotImplemented
		return
	}

	d := op & 0x000F
	t := &traceMessage{
		op:     ops,
		noSize: true,
		dst:    "$%d(PC)",
		args:   []string{"int32(d)"},
	}

	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)

	switch cc {
	default:
		// TODO: implement other conditions
		err = errNotImplemented
		return

	case CondTrue:
		// branch always
		fmt.Fprintln(w, "branch := true")

	case CondEqual:
		// branch if equal
		fmt.Fprintf(w, "branch := c.SR&0x%X != 0\n", StatusZero)
	}

	if d == 0 {
		// 16-bit displacement
		printReadImm(w, "d", SizeWord)
	} else if d == 0x0F {
		// 32-bit displacement
		printReadImm(w, "d", SizeLong)
	} else {
		// 8-bit displacement
		fmt.Fprintln(w, "d := byteToInt32(byte(c.op))")
	}

	// TODO: implement conditions
	fmt.Fprintln(w, "if branch {")
	fmt.Fprintln(w, "	c.PC = uint32(int32(c.PC) + int32(d))")
	fmt.Fprintln(w, "}")
	w.Decrement(1)
	printOpFuncFtr(w, t)
	return w.String(), nil
}

// gen4E implements operations starting in 01001110
func gen4E(op uint16) (fn string, err error) {
	err = errNotImplemented
	if op&0xFF00 != 0x4E00 {
		return
	}
	if op == 0x4E72 {
		fn, err = genStop(op)
	}
	return
}

// genStop implements STOP (6-85)
func genStop(op uint16) (fn string, err error) {
	t := &traceMessage{
		op:     "stop",
		noSize: true,
		dst:    "#$%X",
		args:   []string{"v"},
	}
	w := bufWriter()
	printOpFuncHdr(w, op)
	w.Increment(1)
	printReadImm(w, "v", SizeWord)
	fmt.Fprintln(w, "c.SR = uint32(v)")
	fmt.Fprintln(w, "if c.SR&0x0700 == 0x0700 {")
	fmt.Fprintln(w, "	c.err = io.EOF") // end program is interrupt mask is highest
	fmt.Fprintln(w, "}")
	w.Decrement(1)
	printOpFuncFtr(w, t)
	fn = w.String()
	return
}
